// Code generated by cmd/genmod; DO NOT EDIT.
package mod

// This file imports all modules with module.go so their init() can register.
import (
	_ "backend-go/internal/avatar"
	_ "backend-go/internal/comments"
	_ "backend-go/internal/integrations/aicweb"
	_ "backend-go/internal/redirect"
	_ "backend-go/internal/rhythmgames"
	_ "backend-go/internal/roundnfc"
)
